import React from 'react';

interface DisclaimerModalProps {
  isOpen: boolean;
  requireAccept?: boolean; // if true, user must click Accept to dismiss
  onAccept: () => void;
  onClose?: () => void;
}

export const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ isOpen, requireAccept = false, onAccept, onClose }) => {
  if (!isOpen) return null;

  const handleBackdrop = () => {
    if (!requireAccept && onClose) onClose();
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4" onClick={handleBackdrop}>
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-xl w-full p-6" onClick={e => e.stopPropagation()}>
        <h2 className="text-lg font-semibold text-brand-text-primary dark:text-white">Important Disclaimer</h2>
        <div className="mt-3 text-sm text-brand-text-secondary dark:text-gray-200 space-y-3">
          <p>All figures, projections, and estimates provided by this application are intended solely for general planning and illustrative purposes. They are approximate in nature and should not be interpreted as precise forecasts or guarantees of future results.</p>
          <p>This application and its authors do not provide tax, legal, or investment advice. The information presented is not a substitute for professional advice from a qualified accountant, tax advisor, attorney, or financial planner. You should consult with an appropriately qualified professional before making any financial, tax, or legal decisions.</p>
          <p>You are solely responsible for the accuracy and completeness of the data you enter into this planner. The authors and distributors of this application disclaim any and all liability for losses or damages that may arise, directly or indirectly, from reliance on the information, calculations, or projections generated by the application.</p>
          <p>By proceeding to use this software you acknowledge and accept that the planner provides only estimates and educational guidance, and that you assume full responsibility for any decisions you make based on the planner's output.</p>
        </div>

        <div className="mt-6 flex justify-end space-x-2">
          {requireAccept ? (
            // When acceptance is required (first-load), show only Accept
            <button onClick={onAccept} className="px-4 py-2 rounded-md bg-brand-primary text-white text-sm hover:opacity-95">Accept</button>
          ) : (
            // When not required (header popover), show only Close
            onClose && <button onClick={onClose} className="px-4 py-2 rounded-md border text-sm bg-gray-100 hover:bg-gray-200">Close</button>
          )}
        </div>
      </div>
    </div>
  );
};

export default DisclaimerModal;
