import React, { useState } from 'react';
import { useTheme } from '../hooks/useTheme';

interface DisclaimerModalProps {
  isOpen: boolean;
  requireAccept?: boolean; // if true, user must click Accept to dismiss
  onAccept: () => void;
  onClose?: () => void;
}

export const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ isOpen, requireAccept = false, onAccept, onClose }) => {
  const [activeTab, setActiveTab] = useState<'disclaimer' | 'data-storage' | 'key-assumptions'>('disclaimer');
  const { theme } = useTheme();

  if (!isOpen) return null;

  const handleBackdrop = () => {
    if (!requireAccept && onClose) onClose();
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4" onClick={handleBackdrop}>
      <div 
        className="border border-gray-200 dark:border-slate-700 rounded-lg shadow-xl max-w-xl w-full p-6" 
        style={{ backgroundColor: theme === 'dark' ? '#070f24' : '#ffffff' }}
        onClick={e => e.stopPropagation()}
      >
        <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Important Disclaimer</h2>
        
        {/* Tabs */}
        <div className="mt-4 border-b border-gray-200 dark:border-gray-700">
          <nav className="flex space-x-4">
            <button
              onClick={() => setActiveTab('disclaimer')}
              className={`py-2 px-1 border-b-2 font-medium text-sm ${
                activeTab === 'disclaimer'
                  ? 'border-brand-primary text-brand-primary'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              Disclaimer
            </button>
            <button
              onClick={() => setActiveTab('data-storage')}
              className={`py-2 px-1 border-b-2 font-medium text-sm ${
                activeTab === 'data-storage'
                  ? 'border-brand-primary text-brand-primary'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              Data Storage
            </button>
            <button
              onClick={() => setActiveTab('key-assumptions')}
              className={`py-2 px-1 border-b-2 font-medium text-sm ${
                activeTab === 'key-assumptions'
                  ? 'border-brand-primary text-brand-primary'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              Key Assumptions
            </button>
          </nav>
        </div>

        {/* Tab Content */}
        <div className="mt-3 text-sm text-gray-700 dark:text-gray-300 space-y-3 max-h-96 overflow-y-auto">
          {activeTab === 'disclaimer' && (
            <>
              <p>All figures, projections, and estimates provided by this application are intended solely for general planning and illustrative purposes. They are approximate in nature and should not be interpreted as precise forecasts or guarantees of future results.</p>
              <p>This application and its authors do not provide tax, legal, or investment advice. The information presented is not a substitute for professional advice from a qualified accountant, tax advisor, attorney, or financial planner. You should consult with an appropriately qualified professional before making any financial, tax, or legal decisions.</p>
              <p>You are solely responsible for the accuracy and completeness of the data you enter into this planner. The authors and distributors of this application disclaim any and all liability for losses or damages that may arise, directly or indirectly, from reliance on the information, calculations, or projections generated by the application.</p>
              <p>By proceeding to use this software you acknowledge and accept that the planner provides only estimates and educational guidance, and that you assume full responsibility for any decisions you make based on the planner's output.</p>
            </>
          )}

          {activeTab === 'data-storage' && (
            <p><strong>Data storage:</strong> We do not send, collect, or store any of the personal data you enter into this application on our servers. All inputs remain in your browser (for example in localStorage) or in files you explicitly export; we do not ask for or require identifying information such as your name, email address, or other personal identifiers. If you choose to download or share an exported scenario file, that file is saved to your device only and is under your control.</p>
          )}

          {activeTab === 'key-assumptions' && (
            <p><strong>Key assumptions:</strong> The planner uses a number of simplifying assumptions to produce projections. For example, retirement account contributions are assumed to stop at the retirement age you specify; pensions and Social Security payments begin at the ages you enter and use the indicated survivor percentages; investment returns and inflation are modeled according to the market assumptions you set (average return, volatility, and optional fat-tail settings); tax calculations use simplified bracket estimates rather than a full tax return simulation; required minimum distributions and other regulatory rules are approximated. These and other assumptions are intended to make the tool practical for planning but may not reflect all real-world details—use the results as guidance and consult a professional for firm recommendations.</p>
          )}
        </div>

        <div className="mt-6 flex justify-end space-x-2">
          {requireAccept ? (
            // When acceptance is required (first-load), show only Accept
            <button onClick={onAccept} className="px-4 py-2 rounded-md bg-brand-primary text-white text-sm hover:opacity-95">Accept</button>
          ) : (
            // When not required (header popover), show only Close
            onClose && <button onClick={onClose} className="px-4 py-2 rounded-md border text-sm bg-gray-100 hover:bg-gray-200">Close</button>
          )}
        </div>
      </div>
    </div>
  );
};

export default DisclaimerModal;
